---
name: Feature request
description: Suggest an enhancement for zoho-cliq-release-notifier
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
    validations:
      required: true
